### ISSUE TITLE
Increase PASS_MAX_LENGTH value

### ISSUE THREAD

**Issue by Infra-Red** [anders/pwgen#1]
Hi!
Are there any reasons why PASS_MAX_LENGTH set to 31 symbols? Any chance that this value can be increased? 
Thanks!

**Comment by anders** [comment]
The limit is the same as in the GUI (see Keychain Access). I have a vague recollection of >31 not working properly, especially for "memorable" passwords.

**Comment by anders** [comment]
I increased the limit to 128 in commit 8eed1cc
