### ISSUE TITLE
Is there a way to use memorable and have it not use some characters?

### ISSUE THREAD

**Issue by benmartel** [anders/pwgen#2]
We have a script that fails sometimes when it returns certain characters in the results. Is there a way we can omit certain characters from being generated?

**Comment by anders** [comment]
Do you know what characters make your script fail? I don't think there's any control over how the passwords are generated.

You could do: pwgen -a memorable | grep -v '[problematic characters]'

**Comment by benmartel** [comment]
The problem is with HTML. This describes the problem we are having.
http://stackoverflow.com/questions/12873682/short-way-to-escape-html-in-bash

I think it might be `&` and `<>` just to be safe?
... I think.

**Comment by anders** [comment]
Is the problem solved by using the first suggestion from that page?

`pwgen | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/"/\&quot;/g; s/'"'"'/\&#39;/g'`
