### ISSUE TITLE
Low max length

### ISSUE THREAD

**Issue by Logunov** [anders/pwgen#3]
```bash
$ sf-pwgen -l 50 -c 1 | wc
1       1      32
```

**Comment by anders** [comment]
You'll notice the same thing in Keychain Access if you generate memorable passwords, there's nothing I can do about it.

Try using a different algorithm:
````
$ sf-pwgen -l 50 -c 1 -a random | wc
````

**Comment by Logunov** [comment]
```bash
$ sf-pwgen -l 50 -c 1 -a random | wc
1       1      32
```

**Comment by anders** [comment]
From the source:

````c
// The length limit used to be the same as in Keychain Access (min 8, max 31).
#define PASS_MIN_LENGTH 8
#define PASS_MAX_LENGTH 128
#define PASS_DEFAULT_LENGTH 12
#define PASS_DEFAULT_COUNT 5
````

Apparently the API won't return anything longer than 32 characters.

**Comment by dancek** [comment]
This surprised me too, and I came here to file a bug report. I've been using `sf-pwgen` to generate 32-character passwords for years and only now realized they're actually 31 characters.

@anders would you accept a pull request that either combines multiple return values from the API to get more than 31 characters, or mentions the maximum length in readme and usage? Which is preferable?

**Comment by anders** [comment]
I'm reluctant to add password generation logic, I want the program to be identical to the macOS password assistant.

How about writing a warning message to stderr the first time a password is generated with a shorter than requested length? If I remember correctly it could happen with passwords shorter than 31 characters with the memorable generator.

Something like this:
````
$ sf-pwgen -l 31 -c 3 -a memorable (or random, etc)
password1-foo-bar-ok-length
warning: at least one password generated is shorter than the requested length
made-up-thing:oops
blalbal/adsfs
````

**Comment by dancek** [comment]
Great, I'll try to implement that this weekend.
