### ISSUE TITLE
No utf8 characters printed

### ISSUE THREAD

**Issue by mrclmr** [anders/pwgen#5]
👍 Thanks for this nice tool. I use it a lot because the secure passwords are memorizable.

For example choosing german as language umlauts are not correctly printed:

```
$ sf-pwgen -l 24 -c 3 -L de
Viehfarm5951247_Erlser    # normally 'ö'
speckige863!gesttigter    # normally 'ä'
ntigste5/defilierendes    # normally 'ö'
```

Hopefully 1.5 release will be soon in Homebrew :)

**Comment by anders** [comment]
That is a known issue and happens in macOS too, try the "Passwortassistent" in Keychain Access in "Einprägsam" mode, you'll note that generated passwords lack any letters that would have had umlauts. It used to display garbage, they must have improved it in a recent OS release.

From the --help output:
````
  -L, --language     Generate passwords in a specified language.
                     Languages: en, de, es, fr, it, nl, pt, jp.
                     Note that this feature is broken and will produce garbage, bug: rdar://14889281
````

I suppose I could filter broken characters, but it's better if Apple just fixes the bug on their end. I'll clarify the help message

**Comment by mrclmr** [comment]
Okay, thanks for your response. Let's hope Apple fixes this issue.
